export const PLAYER_COMMANDS = {
  PLAY_PAUSE: "PLAY_PAUSE",
  NEXT_TRACK: "NEXT_TRACK",
  PREVIOUS_TRACK: "PREVIOUS_TRACK",
  VOLUME_UP: "VOLUME_UP",
  VOLUME_DOWN: "VOLUME_DOWN",
  SEEK_FORWARD: "SEEK_FORWARD",
  SEEK_BACKWARD: "SEEK_BACKWARD",
};