"""initial clean schema

Revision ID: 7c056559d57c
Revises: 
Create Date: 2026-03-29 20:26:38.558565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c056559d57c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('folder_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('album', sa.String(), nullable=True),
    sa.Column('scanned_title', sa.String(), nullable=True),
    sa.Column('scanned_artist', sa.String(), nullable=True),
    sa.Column('scanned_album', sa.String(), nullable=True),
    sa.Column('display_title', sa.String(), nullable=True),
    sa.Column('display_artist', sa.String(), nullable=True),
    sa.Column('display_album', sa.String(), nullable=True),
    sa.Column('title_normalized', sa.String(), nullable=True),
    sa.Column('artist_normalized', sa.String(), nullable=True),
    sa.Column('album_normalized', sa.String(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('art_path', sa.String(), nullable=True),
    sa.Column('metadata_source', sa.String(), nullable=False),
    sa.Column('user_edited', sa.Boolean(), nullable=False, server_default='0'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracks'))
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracks_album_normalized'), ['album_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracks_artist_normalized'), ['artist_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracks_file_path'), ['file_path'], unique=True)
        batch_op.create_index(batch_op.f('ix_tracks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracks_title_normalized'), ['title_normalized'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_title_normalized'))
        batch_op.drop_index(batch_op.f('ix_tracks_id'))
        batch_op.drop_index(batch_op.f('ix_tracks_file_path'))
        batch_op.drop_index(batch_op.f('ix_tracks_artist_normalized'))
        batch_op.drop_index(batch_op.f('ix_tracks_album_normalized'))

    op.drop_table('tracks')
    # ### end Alembic commands ###
