"""add audio analysis fields to tracks

Revision ID: 80ecb461bf7c
Revises: 9ab4deda4933
Create Date: 2026-05-07 15:48:10.260395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ecb461bf7c'
down_revision: Union[str, Sequence[str], None] = '9ab4deda4933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_tags_id'))
        batch_op.drop_index(batch_op.f('ix_track_tags_tag_id'))
        batch_op.drop_index(batch_op.f('ix_track_tags_track_id'))

    op.drop_table('track_tags')
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlists_id'))

    op.drop_table('playlists')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_category'))
        batch_op.drop_index(batch_op.f('ix_tags_id'))
        batch_op.drop_index(batch_op.f('ix_tags_name'))

    op.drop_table('tags')
    with op.batch_alter_table('track_tag_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_tag_suggestions_id'))
        batch_op.drop_index(batch_op.f('ix_track_tag_suggestions_status'))
        batch_op.drop_index(batch_op.f('ix_track_tag_suggestions_tag_id'))
        batch_op.drop_index(batch_op.f('ix_track_tag_suggestions_track_id'))

    op.drop_table('track_tag_suggestions')
    with op.batch_alter_table('playlist_tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlist_tracks_id'))

    op.drop_table('playlist_tracks')
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bpm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bpm_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('energy_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('energy_label', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('energy_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('audio_analyzed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('audio_analysis_error', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('audio_analysis_error')
        batch_op.drop_column('audio_analyzed_at')
        batch_op.drop_column('energy_confidence')
        batch_op.drop_column('energy_label')
        batch_op.drop_column('energy_score')
        batch_op.drop_column('bpm_confidence')
        batch_op.drop_column('bpm')

    op.create_table('playlist_tracks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('playlist_id', sa.INTEGER(), nullable=False),
    sa.Column('track_id', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.Column('added_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name=op.f('fk_playlist_tracks_playlist_id_playlists')),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_playlist_tracks_track_id_tracks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playlist_tracks'))
    )
    with op.batch_alter_table('playlist_tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlist_tracks_id'), ['id'], unique=False)

    op.create_table('track_tag_suggestions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('track_id', sa.INTEGER(), nullable=False),
    sa.Column('tag_id', sa.INTEGER(), nullable=False),
    sa.Column('source', sa.VARCHAR(), nullable=False),
    sa.Column('confidence', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('reason', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_track_tag_suggestions_tag_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_track_tag_suggestions_track_id_tracks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_track_tag_suggestions')),
    sa.UniqueConstraint('track_id', 'tag_id', name=op.f('uq_track_tag_suggestion'))
    )
    with op.batch_alter_table('track_tag_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_tag_suggestions_track_id'), ['track_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_track_tag_suggestions_tag_id'), ['tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_track_tag_suggestions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_track_tag_suggestions_id'), ['id'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=1)
        batch_op.create_index(batch_op.f('ix_tags_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_category'), ['category'], unique=False)

    op.create_table('playlists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playlists')),
    sa.UniqueConstraint('name', name=op.f('uq_playlists_name'))
    )
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlists_id'), ['id'], unique=False)

    op.create_table('track_tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('track_id', sa.INTEGER(), nullable=False),
    sa.Column('tag_id', sa.INTEGER(), nullable=False),
    sa.Column('source', sa.VARCHAR(), nullable=False),
    sa.Column('confidence', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_track_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_track_tags_track_id_tracks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_track_tags')),
    sa.UniqueConstraint('track_id', 'tag_id', name=op.f('uq_track_tag'))
    )
    with op.batch_alter_table('track_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_tags_track_id'), ['track_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_track_tags_tag_id'), ['tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_track_tags_id'), ['id'], unique=False)

    # ### end Alembic commands ###
