"""Updating models

Revision ID: 9ab4deda4933
Revises: 7c056559d57c
Create Date: 2026-05-04 18:24:11.168134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab4deda4933'
down_revision: Union[str, Sequence[str], None] = '7c056559d57c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlists_id'))

    op.drop_table('playlists')
    with op.batch_alter_table('playlist_tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlist_tracks_id'))

    op.drop_table('playlist_tracks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_tracks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('playlist_id', sa.INTEGER(), nullable=False),
    sa.Column('track_id', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.Column('added_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name=op.f('fk_playlist_tracks_playlist_id_playlists')),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_playlist_tracks_track_id_tracks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playlist_tracks'))
    )
    with op.batch_alter_table('playlist_tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlist_tracks_id'), ['id'], unique=False)

    op.create_table('playlists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playlists')),
    sa.UniqueConstraint('name', name=op.f('uq_playlists_name'))
    )
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlists_id'), ['id'], unique=False)

    # ### end Alembic commands ###
